### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by lukasbystricky** [EmmaSweeney/philip-james-bailey_festus#1]
Very good work Emma. The formatting is the scans is a mess, no wonder the OCR didn't do a great job.

I don't really have any must-dos, but just a couple questions.

- [ ] Why did you add numbers to the sections? It looks to me like the titles should either be the scene settings, or perhaps the whole thing should be in a single file
- [ ] Why did you add a vertical line next to "Seraphim Cherubim" in the first chapter? Also in the text it says "Seraphim and Cherubim". Was that intentional?

**Comment by EmmaSweeney** [comment]
> Why did you add numbers to the sections? It looks to me like the titles should either be the scene settings, or perhaps the whole thing should be in a single file

Edinburgh University Press's critical edition of Festus edited by Mischa Willett has titles like "Scene 1". [Other PD editions](https://archive.org/details/festuspoem00bailrich/page/20/mode/2up) use roman numerals. It would be hard to navigate this 105,000-word publication with no titles. I thought about using `hidden="hidden"` but some scenes use the same scene descriptions, making it easy to lose track of scenes (myself included).

> Why did you add a vertical line next to "Seraphim Cherubim" in the first chapter? Also in the text it says "Seraphim and Cherubim". Was that intentional?

The together class is used for multiple speakers. See [SEMOS 7.6.5.3](https://standardebooks.org/manual/1.7.3/single-page#7.6.5.3) or the [drama how-to guide](https://standardebooks.org/contribute/how-tos/how-to-conquer-complex-drama-formatting) on more than one personas. This is used especially when the personas have separate dialog.

**Comment by lukasbystricky** [comment]
Ok, that all makes sense.
